<?php

// Auto generated by wpfluent Installer.

return array(
    'name'         => 'Fluent Boards Pro',
    'slug'         => 'fluent-boards-pro',
    'domain_path'  => '/language',
    'text_domain'  => 'fluent-boards-pro',
    'hook_prefix'  => 'fluent_boards_pro',
    'rest_version' => 'v2',
    'env'          => 'dev',
);
