<?php

 // Auto generated by wpfluent Installer.

 return [
     'name'           => 'Fluent Boards',
     'slug'           => 'fluent-boards',
     'domain_path'    => '/language',
     'text_domain'    => 'fluent-boards',
     'hook_prefix'    => 'fluent_boards/',
     'rest_namespace' => 'fluent-boards',
     'rest_version'   => 'v2',
     'env'            => 'dev',
     'timezone'       => 'UTC',
 ];
